name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint
        run: |
          flake8 .
      - name: Test
        run: |
          pytest -q

  docker:
    needs: lint-test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/california-regressor:latest .
      - name: Push
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/california-regressor:latest
